# Generated by Django 5.2.1 on 2025-05-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
